### ISSUE TITLE
SlackNotifier Lambda function is not working

### ISSUE THREAD

**Issue by pporwal0110** [aws-solutions/aws-limit-monitor#77]
Error:

2021-07-16T22:45:07.335Z	f22c518c-7efc-4ead-9309-4038d939873c	ERROR	Uncaught Exception 	{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'status' of undefined",
    "code": "TypeError",
    "message": "Cannot read property 'status' of undefined",
    "time": "2021-07-16T22:45:07.335Z",
    "stack": [
        "TypeError: Cannot read property 'status' of undefined",
        "    at slacknotify.slackMessageBuilder (/var/task/lib/slack-notify.js:90:21)",
        "    at Response.<anonymous> (/var/task/lib/slack-notify.js:66:38)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:369:18)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)"
    ]
}

Kindly help.

**Comment by gsingh04** [comment]
@pporwal0110 

Apologies for the delayed response here. Do you still experience this issue? Can you please provide the steps to recreate this issue at our end? Did you make any customizations to the the solution?

Please let us know, and we will be happy to look into this further.
