### ISSUE TITLE
could this template be used for monitor number of rules used in eventbridge service?

### ISSUE THREAD

**Issue by HCharlie** [aws-solutions/aws-limit-monitor#81]
I want to monitor if the number of event bridge rules that are used in my account is approaching the limit, will the template in this repo work?

**Comment by gsingh04** [comment]
Currently, the solution only supports limits mentioned on this [page](https://docs.aws.amazon.com/awssupport/latest/user/trusted-advisor-check-reference.html#service-limits) + vCPU EC2 service limit (https://aws.amazon.com/ec2/faqs/#EC2_On-Demand_Instance_limits).
